providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build", "cp node_modules/.bin/serve /usr/local/bin/serve"]

[start]
cmd = "serve -s dist"